### PR TITLE
Drop Python 2.6 support for first release. Fixes #22

### LINKED ISSUE #22: Drop Python 2.6 support for first release
Quoting from Python docs:

> Python 2.6 is now in security-fix-only mode; no new features are being added, and no new bug fix releases are planned. We intend to provide source-only security fixes for the Python 2.6 series until October 2013 (five years after the 2.6 final release). For ongoing maintenance releases, please see the Python 2.7 series. The NEWS file lists every change in each alpha, beta, and release candidate of Python 2.6.

TODO: remove `2.6` testing from travis also.

### PR DESCRIPTION
**Pull request by malayaleecoder**
Tries to fix  #22 
@aktech : Have a look :)

### CODE REVIEW

**Comment by aktech** [comment]
Looks good +1
Thanks for the PR.

**Comment by malayaleecoder** [comment]
@aktech : Do you have any other issue or implementation that I can work on ?

**Comment by aktech** [comment]
@malayaleecoder  Yes, there are a lot of things which you can work on like: #26 #4 #12

**Comment by malayaleecoder** [comment]
@aktech : Thanks. Mostly will try with the easy ones like binary search or countsort :) Will try to send a PR for these.

**Pull request merged**
