### PR TITLE
Add Binary Tree implementation, tests

### PR DESCRIPTION
**Pull request by rehassachdeva**
references #4 

Please review.

### CODE REVIEW

**Comment by goelakash** [comment]
Good work! @rehassachdeva . Few comments:

1. `delete` is slightly trickier. You can only delete children node when they are leaf nodes, other wise you have to some adjustments. See this to understand more - http://www.geeksforgeeks.org/write-a-c-program-to-delete-a-tree/

2. Add docstrings to functions to explain the arguments and the operations being performed on them.

**Comment by rehassachdeva** [comment]
Hi @goelakash. Have made the necessary changes. Please check now

**Comment by goelakash** [comment]
Looks good to me. @aktech Can we merge this?

**Comment by goelakash** [comment]
#74 Maybe we can have a separate traversal module, and use those for all tree data structures. @aktech @CuriousLearner What do you guys think?

**Comment by rehassachdeva** [comment]
@goelakash Docs have already been added here #68. I'll add reference for binary_tree once this is merged?

**Comment by goelakash** [comment]
@rehassachdeva That sounds good.

**Comment by aktech** [comment]
@rehassachdeva Please fix conflicts.

**Comment by rehassachdeva** [comment]
@aktech

**Pull request merged**
