### PR TITLE
Remove * import

### PR DESCRIPTION
**Pull request by iamneha**
#59 @aktech @CuriousLearner code base clear for this issue.

### CODE REVIEW

**Comment by aktech** [comment]
Clean code base is a too broad term to be used for this PR. Please rename the title to something like:
"Remove * imports".

**Comment by iamneha** [comment]
should I remove commit message also

**Comment by aktech** [comment]
> should I remove commit message also

Yes, please.

**Comment by iamneha** [comment]
@aktech done

**Comment by aktech** [comment]
Looks good. +1

**Pull request merged**
