### PR TITLE
Adding Mathematical Algorithms

### PR DESCRIPTION
**Pull request by AssualtKoder95**

### CODE REVIEW

**Comment by aktech** [comment]
@AssualtKoder95  Thanks for the PR. Please fix conflicts.

**Comment by rahulroxx** [comment]
@AssualtKoder95 Add tests and resolve conflicts.

**Comment by AssualtKoder95** [comment]
Please review @aktech , i have updated files .

**Comment by CuriousLearner** [comment]
@AssualtKoder95 Please resolve conflicts first!

**Pull request closed without merging**
