### PR TITLE
Add .coafile

### PR DESCRIPTION
**Pull request by SanketDG**
coala (http://coala-analyzer.org/) is a language independent
static analysis tool that can provide patches to source code
errors. This file implements common settings for coala.

A dev-requirements.txt file is added that contains the latest
stable version of coala.

The first step would be to install coala:

```
$ pip install -r dev-requirements.txt
```

So coala uses this .coafile to decide which routines (aka bears) to run. Just running:
```
$ coala
```
would do everything your `white_space.py` currently does! :smile: 

Along with that I have added a few sections that you can run using:
```
$ coala <section_name>
```
The sections are:
```
pylint: Checks the whole codebase against pylint
invalidlinks: Checks docs for invalid links.
imports: Sorts imports! This is pretty trivial, but you may want to take a look.
```

If you need any help in this or want to learn more about the project, feel free to ping us at https://gitter.im/coala-analyzer/coala.

### CODE REVIEW

**Comment by sils1297** [comment]
@SanketDG they already seem to have https://github.com/pydsa/pydsa/blob/master/white_space.py which this would replace, right?

**Comment by aktech** [comment]
@SanketDG Thanks for the PR. 
How about using `requirements.txt` instead of `dev-requirements.txt` ?

**Comment by SanketDG** [comment]
@aktech sure I have updated the PR. Also:

- Would you like to remove `white_space.py`? Since coala now does all of its work.
- `autopep8` shouldn't be in the dependencies IMHO, It should be in a "requirements" file. But since `coala` uses `autopep8` to fix python code, it is not needed and hence can be removed.

Let me know your thoughts.

**Comment by aktech** [comment]
Sorry for the late reply.
> Would you like to remove white_space.py? Since coala now does all of its work.

Yes, sure.

> autopep8 shouldn't be in the dependencies IMHO, It should be in a "requirements" file. But since coala uses autopep8 to fix python code, it is not needed and hence can be removed.

Go ahead.

**Comment by SanketDG** [comment]
@aktech cool! PR's updated, let me know if you need any changes.

**Comment by aktech** [comment]
> PR's updated, let me know if you need any changes.

Great! Can you also add some basic usage instructions on the `README.md` file?

**Comment by SanketDG** [comment]
@aktech Done :smile:

I have also added `py.test` to the list of requirements and accordingly updated the README.

**Comment by aktech** [comment]
@SanketDG Thanks for the PR. Merging. :+1:

**Comment by SanketDG** [comment]
@aktech :+1: :smile:

**Pull request merged**
